// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teledoc.Infrastructure.DataContext;

#nullable disable

namespace Teledoc.Infrastructure.Migrations
{
    [DbContext(typeof(ClientDbContext))]
    partial class ClientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teledoc.Domain.BoundedContexts.ClientManagement.Aggregates.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientTypeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Teledoc.Domain.BoundedContexts.ClientManagement.Aggregates.Founder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("Teledoc.Domain.BoundedContexts.ClientManagement.ValueObjects.ClientType.ClientType", b =>
                {
                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<int>("ClientTypeIdValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Value");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("ClientTypes");

                    b.HasData(
                        new
                        {
                            Value = 1,
                            ClientTypeIdValue = 1,
                            Name = "IndividualEntrepreneur"
                        },
                        new
                        {
                            Value = 2,
                            ClientTypeIdValue = 2,
                            Name = "LegalEntity"
                        });
                });

            modelBuilder.Entity("Teledoc.Domain.BoundedContexts.ClientManagement.Aggregates.Client", b =>
                {
                    b.HasOne("Teledoc.Domain.BoundedContexts.ClientManagement.ValueObjects.ClientType.ClientType", null)
                        .WithMany()
                        .HasForeignKey("ClientTypeId")
                        .HasPrincipalKey("ClientTypeIdValue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Teledoc.Domain.BoundedContexts.ClientManagement.ValueObjects.Composite.INN", "INN", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("INN");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients", t =>
                                {
                                    t.HasCheckConstraint("CK_Client_INN_Length", "LEN(INN) = 12");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("INN")
                        .IsRequired();
                });

            modelBuilder.Entity("Teledoc.Domain.BoundedContexts.ClientManagement.Aggregates.Founder", b =>
                {
                    b.HasOne("Teledoc.Domain.BoundedContexts.ClientManagement.Aggregates.Client", null)
                        .WithMany("Founders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Teledoc.Domain.BoundedContexts.ClientManagement.ValueObjects.Composite.INN", "INN", b1 =>
                        {
                            b1.Property<int>("FounderId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("INN");

                            b1.HasKey("FounderId");

                            b1.ToTable("Founders", t =>
                                {
                                    t.HasCheckConstraint("CK_Founder_INN_Length", "LEN(INN) = 12");
                                });

                            b1.WithOwner()
                                .HasForeignKey("FounderId");
                        });

                    b.OwnsOne("Teledoc.Domain.BoundedContexts.ClientManagement.ValueObjects.Composite.UserFullName", "FullName", b1 =>
                        {
                            b1.Property<int>("FounderId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("UserName");

                            b1.HasKey("FounderId");

                            b1.ToTable("Founders");

                            b1.WithOwner()
                                .HasForeignKey("FounderId");
                        });

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("INN")
                        .IsRequired();
                });

            modelBuilder.Entity("Teledoc.Domain.BoundedContexts.ClientManagement.Aggregates.Client", b =>
                {
                    b.Navigation("Founders");
                });
#pragma warning restore 612, 618
        }
    }
}
